export const testLocationForecasts = [
{
"id": 81,
"accessedDate": "2023-04-12T14:57:21.507+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "A clear sky and light winds",
"gustSpeedKph": 7,
"feelsLikeTemperatureC": "9",
"feelsLikeTemperatureF": "49",
"humidity": 80,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 15,
"precipitationProbabilityText": "Low chance of precipitation",
"pressure": 1021,
"temperatureC": 9,
"temperatureF": 49,
"timeslot": "00:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Clear Sky",
"windDescription": "Light winds from the south south west",
"windDirection": "SSW",
"windDirectionAbbreviation": "SSW",
"windDirectionFull": "South South Westerly",
"windSpeedKph": 6,
"windSpeedMph": 4
},
{
"id": 82,
"accessedDate": "2023-04-12T14:57:21.508+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 7,
"feelsLikeTemperatureC": "9",
"feelsLikeTemperatureF": "48",
"humidity": 84,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 15,
"precipitationProbabilityText": "Low chance of precipitation",
"pressure": 1021,
"temperatureC": 9,
"temperatureF": 48,
"timeslot": "01:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 6,
"windSpeedMph": 4
},
{
"id": 83,
"accessedDate": "2023-04-12T14:57:21.508+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 5,
"feelsLikeTemperatureC": "8",
"feelsLikeTemperatureF": "47",
"humidity": 87,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1021,
"temperatureC": 8,
"temperatureF": 47,
"timeslot": "02:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south south west",
"windDirection": "SSW",
"windDirectionAbbreviation": "SSW",
"windDirectionFull": "South South Westerly",
"windSpeedKph": 6,
"windSpeedMph": 4
},
{
"id": 84,
"accessedDate": "2023-04-12T14:57:21.508+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 6,
"feelsLikeTemperatureC": "8",
"feelsLikeTemperatureF": "47",
"humidity": 89,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1021,
"temperatureC": 8,
"temperatureF": 47,
"timeslot": "03:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 5,
"windSpeedMph": 3
},
{
"id": 85,
"accessedDate": "2023-04-12T14:57:21.509+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 6,
"feelsLikeTemperatureC": "8",
"feelsLikeTemperatureF": "47",
"humidity": 91,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1021,
"temperatureC": 8,
"temperatureF": 47,
"timeslot": "04:00",
"timeslotLength": 1,
"visibility": "Moderate",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 5,
"windSpeedMph": 3
},
{
"id": 86,
"accessedDate": "2023-04-12T14:57:21.509+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 4,
"feelsLikeTemperatureC": "8",
"feelsLikeTemperatureF": "46",
"humidity": 92,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1021,
"temperatureC": 8,
"temperatureF": 46,
"timeslot": "05:00",
"timeslotLength": 1,
"visibility": "Moderate",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 4,
"windSpeedMph": 3
},
{
"id": 87,
"accessedDate": "2023-04-12T14:57:21.509+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 5,
"feelsLikeTemperatureC": "8",
"feelsLikeTemperatureF": "47",
"humidity": 90,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1021,
"temperatureC": 8,
"temperatureF": 47,
"timeslot": "06:00",
"timeslotLength": 1,
"visibility": "Moderate",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south south west",
"windDirection": "SSW",
"windDirectionAbbreviation": "SSW",
"windDirectionFull": "South South Westerly",
"windSpeedKph": 4,
"windSpeedMph": 2
},
{
"id": 88,
"accessedDate": "2023-04-12T14:57:21.510+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 5,
"feelsLikeTemperatureC": "8",
"feelsLikeTemperatureF": "46",
"humidity": 90,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1022,
"temperatureC": 8,
"temperatureF": 46,
"timeslot": "07:00",
"timeslotLength": 1,
"visibility": "Moderate",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south south west",
"windDirection": "SSW",
"windDirectionAbbreviation": "SSW",
"windDirectionFull": "South South Westerly",
"windSpeedKph": 4,
"windSpeedMph": 3
},
{
"id": 89,
"accessedDate": "2023-04-12T14:57:21.510+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 6,
"feelsLikeTemperatureC": "9",
"feelsLikeTemperatureF": "48",
"humidity": 88,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1022,
"temperatureC": 9,
"temperatureF": 48,
"timeslot": "08:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south south west",
"windDirection": "SSW",
"windDirectionAbbreviation": "SSW",
"windDirectionFull": "South South Westerly",
"windSpeedKph": 4,
"windSpeedMph": 2
},
{
"id": 90,
"accessedDate": "2023-04-12T14:57:21.510+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 6,
"feelsLikeTemperatureC": "11",
"feelsLikeTemperatureF": "51",
"humidity": 82,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1023,
"temperatureC": 11,
"temperatureF": 51,
"timeslot": "09:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 5,
"windSpeedMph": 3
},
{
"id": 91,
"accessedDate": "2023-04-12T14:57:21.511+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 7,
"feelsLikeTemperatureC": "12",
"feelsLikeTemperatureF": "54",
"humidity": 76,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1023,
"temperatureC": 12,
"temperatureF": 53,
"timeslot": "10:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 5,
"windSpeedMph": 3
},
{
"id": 92,
"accessedDate": "2023-04-12T14:57:21.511+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 8,
"feelsLikeTemperatureC": "13",
"feelsLikeTemperatureF": "56",
"humidity": 69,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1023,
"temperatureC": 13,
"temperatureF": 56,
"timeslot": "11:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 5,
"windSpeedMph": 3
},
{
"id": 93,
"accessedDate": "2023-04-12T14:57:21.511+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 8,
"feelsLikeTemperatureC": "15",
"feelsLikeTemperatureF": "58",
"humidity": 63,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1023,
"temperatureC": 15,
"temperatureF": 58,
"timeslot": "12:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 7,
"windSpeedMph": 4
},
{
"id": 94,
"accessedDate": "2023-04-12T14:57:21.512+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 9,
"feelsLikeTemperatureC": "16",
"feelsLikeTemperatureF": "60",
"humidity": 58,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 16,
"temperatureF": 60,
"timeslot": "13:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 7,
"windSpeedMph": 5
},
{
"id": 95,
"accessedDate": "2023-04-12T14:57:21.512+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 10,
"feelsLikeTemperatureC": "16",
"feelsLikeTemperatureF": "61",
"humidity": 53,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 16,
"temperatureF": 61,
"timeslot": "14:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the west south west",
"windDirection": "WSW",
"windDirectionAbbreviation": "WSW",
"windDirectionFull": "West South Westerly",
"windSpeedKph": 8,
"windSpeedMph": 5
},
{
"id": 96,
"accessedDate": "2023-04-12T14:57:21.512+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Light cloud and light winds",
"gustSpeedKph": 10,
"feelsLikeTemperatureC": "17",
"feelsLikeTemperatureF": "62",
"humidity": 51,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 17,
"temperatureF": 62,
"timeslot": "15:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Light Cloud",
"windDescription": "Light winds from the west south west",
"windDirection": "WSW",
"windDirectionAbbreviation": "WSW",
"windDirectionFull": "West South Westerly",
"windSpeedKph": 9,
"windSpeedMph": 6
},
{
"id": 97,
"accessedDate": "2023-04-12T14:57:21.513+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Light cloud and light winds",
"gustSpeedKph": 9,
"feelsLikeTemperatureC": "17",
"feelsLikeTemperatureF": "62",
"humidity": 51,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 17,
"temperatureF": 62,
"timeslot": "16:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Light Cloud",
"windDescription": "Light winds from the west south west",
"windDirection": "WSW",
"windDirectionAbbreviation": "WSW",
"windDirectionFull": "West South Westerly",
"windSpeedKph": 9,
"windSpeedMph": 6
},
{
"id": 98,
"accessedDate": "2023-04-12T14:57:21.513+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 9,
"feelsLikeTemperatureC": "16",
"feelsLikeTemperatureF": "61",
"humidity": 54,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 16,
"temperatureF": 61,
"timeslot": "17:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the west south west",
"windDirection": "WSW",
"windDirectionAbbreviation": "WSW",
"windDirectionFull": "West South Westerly",
"windSpeedKph": 8,
"windSpeedMph": 5
},
{
"id": 99,
"accessedDate": "2023-04-12T14:57:21.513+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 9,
"feelsLikeTemperatureC": "16",
"feelsLikeTemperatureF": "60",
"humidity": 58,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 16,
"temperatureF": 60,
"timeslot": "18:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the west south west",
"windDirection": "WSW",
"windDirectionAbbreviation": "WSW",
"windDirectionFull": "West South Westerly",
"windSpeedKph": 8,
"windSpeedMph": 5
},
{
"id": 100,
"accessedDate": "2023-04-12T14:57:21.514+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 9,
"feelsLikeTemperatureC": "15",
"feelsLikeTemperatureF": "59",
"humidity": 60,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 15,
"temperatureF": 59,
"timeslot": "19:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 8,
"windSpeedMph": 5
},
{
"id": 101,
"accessedDate": "2023-04-12T14:57:21.514+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Light cloud and light winds",
"gustSpeedKph": 9,
"feelsLikeTemperatureC": "14",
"feelsLikeTemperatureF": "57",
"humidity": 67,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1025,
"temperatureC": 14,
"temperatureF": 57,
"timeslot": "20:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Light Cloud",
"windDescription": "Light winds from the south south west",
"windDirection": "SSW",
"windDirectionAbbreviation": "SSW",
"windDirectionFull": "South South Westerly",
"windSpeedKph": 8,
"windSpeedMph": 5
},
{
"id": 102,
"accessedDate": "2023-04-12T14:57:21.514+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 8,
"feelsLikeTemperatureC": "13",
"feelsLikeTemperatureF": "55",
"humidity": 73,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1025,
"temperatureC": 13,
"temperatureF": 55,
"timeslot": "21:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south",
"windDirection": "S",
"windDirectionAbbreviation": "S",
"windDirectionFull": "Southerly",
"windSpeedKph": 8,
"windSpeedMph": 5
},
{
"id": 103,
"accessedDate": "2023-04-12T14:57:21.515+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 8,
"feelsLikeTemperatureC": "12",
"feelsLikeTemperatureF": "53",
"humidity": 83,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1026,
"temperatureC": 11,
"temperatureF": 53,
"timeslot": "22:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south",
"windDirection": "S",
"windDirectionAbbreviation": "S",
"windDirectionFull": "Southerly",
"windSpeedKph": 7,
"windSpeedMph": 5
},
{
"id": 104,
"accessedDate": "2023-04-12T14:57:21.515+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 8,
"feelsLikeTemperatureC": "11",
"feelsLikeTemperatureF": "52",
"humidity": 85,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1026,
"temperatureC": 11,
"temperatureF": 52,
"timeslot": "23:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south",
"windDirection": "S",
"windDirectionAbbreviation": "S",
"windDirectionFull": "Southerly",
"windSpeedKph": 7,
"windSpeedMph": 4
},
{
"id": 2331,
"accessedDate": "2023-04-13T20:32:49.547+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "A clear sky and light winds",
"gustSpeedKph": 4,
"feelsLikeTemperatureC": "8",
"feelsLikeTemperatureF": "47",
"humidity": 78,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1022,
"temperatureC": 8,
"temperatureF": 47,
"timeslot": "00:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Clear Sky",
"windDescription": "Light winds from the south south west",
"windDirection": "SSW",
"windDirectionAbbreviation": "SSW",
"windDirectionFull": "South South Westerly",
"windSpeedKph": 5,
"windSpeedMph": 3
},
{
"id": 2332,
"accessedDate": "2023-04-13T20:32:49.547+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "A clear sky and light winds",
"gustSpeedKph": 4,
"feelsLikeTemperatureC": "8",
"feelsLikeTemperatureF": "47",
"humidity": 82,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1022,
"temperatureC": 8,
"temperatureF": 47,
"timeslot": "01:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Clear Sky",
"windDescription": "Light winds from the south",
"windDirection": "S",
"windDirectionAbbreviation": "S",
"windDirectionFull": "Southerly",
"windSpeedKph": 4,
"windSpeedMph": 2
},
{
"id": 2333,
"accessedDate": "2023-04-13T20:32:49.548+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "A clear sky and light winds",
"gustSpeedKph": 3,
"feelsLikeTemperatureC": "8",
"feelsLikeTemperatureF": "46",
"humidity": 86,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1022,
"temperatureC": 8,
"temperatureF": 46,
"timeslot": "02:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Clear Sky",
"windDescription": "Light winds from the south south west",
"windDirection": "SSW",
"windDirectionAbbreviation": "SSW",
"windDirectionFull": "South South Westerly",
"windSpeedKph": 4,
"windSpeedMph": 2
},
{
"id": 2334,
"accessedDate": "2023-04-13T20:32:49.548+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 4,
"feelsLikeTemperatureC": "7",
"feelsLikeTemperatureF": "45",
"humidity": 87,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1022,
"temperatureC": 8,
"temperatureF": 46,
"timeslot": "03:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 3,
"windSpeedMph": 2
},
{
"id": 2335,
"accessedDate": "2023-04-13T20:32:49.549+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 3,
"feelsLikeTemperatureC": "7",
"feelsLikeTemperatureF": "45",
"humidity": 89,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1022,
"temperatureC": 7,
"temperatureF": 45,
"timeslot": "04:00",
"timeslotLength": 1,
"visibility": "Moderate",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 3,
"windSpeedMph": 2
},
{
"id": 2336,
"accessedDate": "2023-04-13T20:32:49.549+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 3,
"feelsLikeTemperatureC": "7",
"feelsLikeTemperatureF": "45",
"humidity": 90,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1023,
"temperatureC": 7,
"temperatureF": 45,
"timeslot": "05:00",
"timeslotLength": 1,
"visibility": "Moderate",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 3,
"windSpeedMph": 2
},
{
"id": 2337,
"accessedDate": "2023-04-13T20:32:49.550+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Partly cloudy and light winds",
"gustSpeedKph": 3,
"feelsLikeTemperatureC": "7",
"feelsLikeTemperatureF": "44",
"humidity": 89,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1023,
"temperatureC": 7,
"temperatureF": 45,
"timeslot": "06:00",
"timeslotLength": 1,
"visibility": "Moderate",
"weatherTypeText": "Partly Cloudy",
"windDescription": "Light winds from the south south west",
"windDirection": "SSW",
"windDirectionAbbreviation": "SSW",
"windDirectionFull": "South South Westerly",
"windSpeedKph": 3,
"windSpeedMph": 2
},
{
"id": 2338,
"accessedDate": "2023-04-13T20:32:49.550+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 4,
"feelsLikeTemperatureC": "7",
"feelsLikeTemperatureF": "45",
"humidity": 88,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1023,
"temperatureC": 7,
"temperatureF": 45,
"timeslot": "07:00",
"timeslotLength": 1,
"visibility": "Moderate",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south",
"windDirection": "S",
"windDirectionAbbreviation": "S",
"windDirectionFull": "Southerly",
"windSpeedKph": 3,
"windSpeedMph": 2
},
{
"id": 2339,
"accessedDate": "2023-04-13T20:32:49.551+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 4,
"feelsLikeTemperatureC": "8",
"feelsLikeTemperatureF": "47",
"humidity": 86,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1023,
"temperatureC": 8,
"temperatureF": 47,
"timeslot": "08:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south",
"windDirection": "S",
"windDirectionAbbreviation": "S",
"windDirectionFull": "Southerly",
"windSpeedKph": 2,
"windSpeedMph": 1
},
{
"id": 2340,
"accessedDate": "2023-04-13T20:32:49.551+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 5,
"feelsLikeTemperatureC": "10",
"feelsLikeTemperatureF": "50",
"humidity": 80,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 10,
"temperatureF": 50,
"timeslot": "09:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south",
"windDirection": "S",
"windDirectionAbbreviation": "S",
"windDirectionFull": "Southerly",
"windSpeedKph": 3,
"windSpeedMph": 2
},
{
"id": 2341,
"accessedDate": "2023-04-13T20:32:49.551+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny and light winds",
"gustSpeedKph": 6,
"feelsLikeTemperatureC": "12",
"feelsLikeTemperatureF": "53",
"humidity": 73,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 12,
"temperatureF": 53,
"timeslot": "10:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny",
"windDescription": "Light winds from the south south west",
"windDirection": "SSW",
"windDirectionAbbreviation": "SSW",
"windDirectionFull": "South South Westerly",
"windSpeedKph": 3,
"windSpeedMph": 2
},
{
"id": 2342,
"accessedDate": "2023-04-13T20:32:49.552+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 7,
"feelsLikeTemperatureC": "13",
"feelsLikeTemperatureF": "56",
"humidity": 66,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 13,
"temperatureF": 56,
"timeslot": "11:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south south west",
"windDirection": "SSW",
"windDirectionAbbreviation": "SSW",
"windDirectionFull": "South South Westerly",
"windSpeedKph": 4,
"windSpeedMph": 2
},
{
"id": 2343,
"accessedDate": "2023-04-13T20:32:49.552+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 7,
"feelsLikeTemperatureC": "14",
"feelsLikeTemperatureF": "57",
"humidity": 59,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 14,
"temperatureF": 58,
"timeslot": "12:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south south west",
"windDirection": "SSW",
"windDirectionAbbreviation": "SSW",
"windDirectionFull": "South South Westerly",
"windSpeedKph": 5,
"windSpeedMph": 3
},
{
"id": 2344,
"accessedDate": "2023-04-13T20:32:49.553+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Light cloud and light winds",
"gustSpeedKph": 8,
"feelsLikeTemperatureC": "15",
"feelsLikeTemperatureF": "59",
"humidity": 54,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 15,
"temperatureF": 59,
"timeslot": "13:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Light Cloud",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 5,
"windSpeedMph": 3
},
{
"id": 2345,
"accessedDate": "2023-04-13T20:32:49.553+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 9,
"feelsLikeTemperatureC": "16",
"feelsLikeTemperatureF": "60",
"humidity": 52,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 16,
"temperatureF": 60,
"timeslot": "14:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south west",
"windDirection": "SW",
"windDirectionAbbreviation": "SW",
"windDirectionFull": "South Westerly",
"windSpeedKph": 6,
"windSpeedMph": 4
},
{
"id": 2346,
"accessedDate": "2023-04-13T20:32:49.553+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 10,
"feelsLikeTemperatureC": "16",
"feelsLikeTemperatureF": "61",
"humidity": 48,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 16,
"temperatureF": 61,
"timeslot": "15:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the west south west",
"windDirection": "WSW",
"windDirectionAbbreviation": "WSW",
"windDirectionFull": "West South Westerly",
"windSpeedKph": 8,
"windSpeedMph": 5
},
{
"id": 2347,
"accessedDate": "2023-04-13T20:32:49.554+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 10,
"feelsLikeTemperatureC": "16",
"feelsLikeTemperatureF": "61",
"humidity": 48,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 16,
"temperatureF": 61,
"timeslot": "16:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the west south west",
"windDirection": "WSW",
"windDirectionAbbreviation": "WSW",
"windDirectionFull": "West South Westerly",
"windSpeedKph": 9,
"windSpeedMph": 5
},
{
"id": 2348,
"accessedDate": "2023-04-13T20:32:49.555+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 11,
"feelsLikeTemperatureC": "15",
"feelsLikeTemperatureF": "60",
"humidity": 52,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 16,
"temperatureF": 60,
"timeslot": "17:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the west south west",
"windDirection": "WSW",
"windDirectionAbbreviation": "WSW",
"windDirectionFull": "West South Westerly",
"windSpeedKph": 8,
"windSpeedMph": 5
},
{
"id": 2349,
"accessedDate": "2023-04-13T20:32:49.555+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 12,
"feelsLikeTemperatureC": "15",
"feelsLikeTemperatureF": "58",
"humidity": 57,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1024,
"temperatureC": 15,
"temperatureF": 59,
"timeslot": "18:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the west south west",
"windDirection": "WSW",
"windDirectionAbbreviation": "WSW",
"windDirectionFull": "West South Westerly",
"windSpeedKph": 8,
"windSpeedMph": 5
},
{
"id": 2350,
"accessedDate": "2023-04-13T20:32:49.556+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "Sunny intervals and light winds",
"gustSpeedKph": 9,
"feelsLikeTemperatureC": "14",
"feelsLikeTemperatureF": "57",
"humidity": 59,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1025,
"temperatureC": 14,
"temperatureF": 58,
"timeslot": "19:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Sunny Intervals",
"windDescription": "Light winds from the south",
"windDirection": "S",
"windDirectionAbbreviation": "S",
"windDirectionFull": "Southerly",
"windSpeedKph": 7,
"windSpeedMph": 5
},
{
"id": 2351,
"accessedDate": "2023-04-13T20:32:49.556+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "A clear sky and light winds",
"gustSpeedKph": 9,
"feelsLikeTemperatureC": "13",
"feelsLikeTemperatureF": "55",
"humidity": 64,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1025,
"temperatureC": 13,
"temperatureF": 56,
"timeslot": "20:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Clear Sky",
"windDescription": "Light winds from the south",
"windDirection": "S",
"windDirectionAbbreviation": "S",
"windDirectionFull": "Southerly",
"windSpeedKph": 8,
"windSpeedMph": 5
},
{
"id": 2352,
"accessedDate": "2023-04-13T20:32:49.557+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "A clear sky and light winds",
"gustSpeedKph": 9,
"feelsLikeTemperatureC": "11",
"feelsLikeTemperatureF": "53",
"humidity": 70,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1026,
"temperatureC": 12,
"temperatureF": 53,
"timeslot": "21:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Clear Sky",
"windDescription": "Light winds from the south east",
"windDirection": "SE",
"windDirectionAbbreviation": "SE",
"windDirectionFull": "South Easterly",
"windSpeedKph": 8,
"windSpeedMph": 5
},
{
"id": 2353,
"accessedDate": "2023-04-13T20:32:49.557+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "A clear sky and light winds",
"gustSpeedKph": 8,
"feelsLikeTemperatureC": "10",
"feelsLikeTemperatureF": "50",
"humidity": 80,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1026,
"temperatureC": 10,
"temperatureF": 51,
"timeslot": "22:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Clear Sky",
"windDescription": "Light winds from the east south east",
"windDirection": "ESE",
"windDirectionAbbreviation": "ESE",
"windDirectionFull": "East South Easterly",
"windSpeedKph": 8,
"windSpeedMph": 5
},
{
"id": 2354,
"accessedDate": "2023-04-13T20:32:49.558+00:00",
"location": {
"id": "2643743",
"locationName": "London"
},
"enhancedWeatherDescription": "A clear sky and light winds",
"gustSpeedKph": 7,
"feelsLikeTemperatureC": "10",
"feelsLikeTemperatureF": "49",
"humidity": 84,
"localDate": "2023-04-16",
"precipitationProbabilityInPercent": 0,
"precipitationProbabilityText": "Precipitation is not expected",
"pressure": 1026,
"temperatureC": 10,
"temperatureF": 49,
"timeslot": "23:00",
"timeslotLength": 1,
"visibility": "Good",
"weatherTypeText": "Clear Sky",
"windDescription": "Light winds from the east south east",
"windDirection": "ESE",
"windDirectionAbbreviation": "ESE",
"windDirectionFull": "East South Easterly",
"windSpeedKph": 7,
"windSpeedMph": 4
}
]